#############
POST https://backend-labweb.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "name": "Lázaro",
    "email": "lazarodu@gmail.com",
    "password": "1234"
}


#############
POST https://backend-labweb.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "lazarodu@gmail.com",
    "password": "1234"
}